### ISSUE TITLE
Redo the calculations with network size = 2000

### ISSUE THREAD

**Issue by albertocottica** [albertocottica/communities-network-design#3]
The first thing we do is to re-run the code as follows. All networks should be grown to size 2000 to make sure that in-degree spans across 2.5 degrees of magnitude.
1. no onboarding (control group)
2. nu1 = nu2 = 0
3. nu1 = 0.2, nu2 = 0
4. nu1 = 0.4, nu2 = 0
   ...
   8 nu1 = 0.4, nu2 = 0 
   etc. 

Notice that, when nu1 = 0, the onboarded person does not do anything. So, whatever the value of nu2, the network will always be the same as with nu1 = nu2 = 0

**Comment by guywiz** [comment]
It's just as if it was already done. I'll keep you posted when results are
available.

Guy Melançon - guywiz

http://about.me/guywiz

http://www.labri.fr/perso/melancon

http://guy.melancon.emi.u-bordeaux1.fr/

##

**Comment by renoust** [comment]
Just to make sure, we've got to do all the combinations of nu1 and nu2 as
given. I may do the say with other the data sets & pictures, because
Alberto, you have a version only with nu1 = nu2 right now.

## 

Benjamin

**Comment by guywiz** [comment]
"I may do the say with other the data sets & pictures"

What do you mean exactly ...? Is this Japanese? [?]

Guy Melançon - guywiz

http://about.me/guywiz

http://www.labri.fr/perso/melancon

http://guy.melancon.emi.u-bordeaux1.fr/

##

**Comment by renoust** [comment]
This is exhaustion Guy, I haven't slept yet since your saturday night, and
it's monday night here...
I have launched data sets for Alberto, and did visualizations from the
following parameters:

networkSize=2000
m = a = 1
nu in [0, 0.2, 0.4, 0.6, 0.8, 1](which is referred as alpha and gamma in
the code, this has to be changed in the final version)
- 1 without onboarding.

So the next step is
nu1 = alpha in  [0, 0.2, 0.4, 0.6, 0.8, 1]
for each nu1
       nu2 = gamma in [0, 0.2, 0.4, 0.6, 0.8, 1]

Then output the right datasets, and draw the right networks accordingly.

Is it right Alberto?
I'm getting a bit nervous on the parameterization of this because last week
we completely misunderstood the thing acting on rush.
So it's better to be extremely clear in algorithmic terms, very pragmatic,
and confirm what parameter we want to feed our main.

## 

Benjamin

**Comment by guywiz** [comment]
I launched the computations accordingly, but discarded the cases nu1 == nu2. The computation is ongoing. Already available results have been uploaded on GDrive this morning.

**Comment by renoust** [comment]
Ha, I think I've misread again.
The computation should be:

nu1 = alpha in  [0, 0.2, 0.4, 0.6, 0.8, 1]
for each nu1
       nu2 = gamma in [0 ... nu1]

this includes also nu1 == nu2

do you confirm?

## 

Benjamin

**Comment by albertocottica** [comment]
nu1 == nu2 needs to be recomputed _if_ the previous runs used a network
size of 650 instead of 2000. :-)

**Comment by guywiz** [comment]
So recomputed they will be.

But then, do we take nu1 = nu2 = sqrt(X) for X in {0.0, 0.2, 0.4, 0.6, 0.8, 1.0}?

—

Le 3 juin 2015 à 00:48, Alberto Cottica notifications@github.com a écrit :

> nu1 == nu2 needs to be recomputed _if_ the previous runs used a network
> size of 650 instead of 2000. :-)
> 
> On Tue, Jun 2, 2015 at 9:58 AM, Benjamin Renoust notifications@github.com
> wrote:
> 
> > Ha, I think I've misread again.
> > The computation should be:
> > 
> > nu1 = alpha in [0, 0.2, 0.4, 0.6, 0.8, 1]
> > for each nu1
> > nu2 = gamma in [0 ... nu1]
> > 
> > this includes also nu1 == nu2
> > 
> > do you confirm?
> > 
> > ## 
> > 
> > Benjamin
> > 
> > On 2 June 2015 at 09:54, guywiz notifications@github.com wrote:
> > 
> > > I launched the computations accordingly, but discarded the cases nu1 ==
> > > nu2. The computation is ongoing. Already available results have been
> > > uploaded on GDrive this morning.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > > https://github.com/albertocottica/communities-network-design/issues/3#issuecomment-107846326
> > > 
> > > .
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/albertocottica/communities-network-design/issues/3#issuecomment-107848171
> > .
> > 
> > —
> > Reply to this email directly or view it on GitHub.

Guy Melançon - guywiz
GMail - guywiz@gmail.com
52 Route de Bernos
33430 Bernos-Beaulac
T. 0556651558 / 0631396671
—
http://about.me/guywiz
http://www.labri.fr/perso/melancon
http://guy.melancon.emi.u-bordeaux1.fr/
—

**Comment by albertocottica** [comment]
No. In this case we simply let nu1 and nu2 vary between 0 and 1 with .2
increments.

**Comment by renoust** [comment]
Guy, I think it's really:
_nu1 = alpha in  [0, 0.2, 0.4, 0.6, 0.8, 1]for each nu1_
-       nu2 = gamma in [0 ... nu1]*

_(so nu2 <= nu1)_

## 

Benjamin

**Comment by renoust** [comment]
(resending, Guy disappeared from the mailing list)

Guy, I think it's really:
_nu1 = alpha in  [0, 0.2, 0.4, 0.6, 0.8, 1]for each nu1_
-       nu2 = gamma in [0 ... nu1]*

_(so nu2 <= nu1)_

## 

Benjamin

**Comment by renoust** [comment]
Friends,

I am relaunching computations as well.

Here are the parameters we are launching:

_m_ = 1
_a_ = 1
_nb_runs_ = 2500
_networkSize_ = 2000

_nu1_ in [0.0, 0.2, 0.4, 0.6, 0.8, 1.0]:
   _nu2_ in [0.0 .. nu1]

notice that we actually compute :
_alpha = sqrt(nu1), *
*gamma = sqrt(nu2)_

The whole lists of degrees with parameters are in the drive in the
subfolder 'Code/results/', under the shape:

_DegreesOfOnBoardingModel_with_onboarding_size_2000_m_1_a_1_alpha_0.000000_gamma_0.000000.json_
stating
"the degrees of the onboarding model, with onboarding, of network
size=2000, with parameters a=1, m=1, alpha = 0.0, gamma=0.0"

(it is a json readable list of the form [....] of actual size=size+2
because of our initialization)

We also fin the graphs in their GEXF forms.
I am proposing to visualize them, as in my previous mail, (and the pictures
available in Code/results/images/), but I'm waiting for
Alberto's feedback before tackling any other new visualization. Note that
the onboard modeling also includes multiple edges, of
quantity that unsurprisingly grows with the density of edges.

## 

Benjamin

**Comment by albertocottica** [comment]
Ben,

are we using GitHub or GDrive? I prefer GitHub, but if you want Gdrive
that's fine too. Using both is _not_ fine for me :-)

**Comment by albertocottica** [comment]
Also, Ben, I cannot find code/results/images neither in Gdrive nor in
GitHub :-(

**Comment by renoust** [comment]
The paper is on GitHub, the code on GDrive.
I'm following your scheme :)

Here are the old images:
https://github.com/albertocottica/communities-network-design/tree/master/images
Here is the code and result so far:
https://drive.google.com/folderview?id=0B_vWawrKpTaFfi1zTUFweDVZV0JmQnhnRTVHdExwRklBQUtBOUw1bmpnM2dYZGF3VVVtSlk&usp=sharing

## 

Benjamin

**Comment by albertocottica** [comment]
no, no. everything on github please! I prefer the code is uploaded  by Guy,
who has the latest version.

**Comment by renoust** [comment]
Of course I agree :) but since I'm not properly coding, but outputing
results on my own so I can work you Tulip graphs...
I use what I have, and what I have is on GDrive :)

## 

Benjamin

**Comment by albertocottica** [comment]
Ok, look: I can't find them. At one point I did find a "Pictures" folder in
"Sunbelt paper", but it says you (the owner) have moved it into your bin.
:-(

**Comment by renoust** [comment]
Very good then!
I see your life is really on the road, no possible comparison with Guy's or
my own rythme... I'm impressed how you can manage everything together!

So you don't have much time, and mail-time gets thin. Let's go to what's
essential.
- Now everything is on Github and solely on Github, Alberto, you're
  chairing the paper, Guy is chairing the code, I am chairing the vis
- Alberto, can you share your charting code with us, it's much better than
  what I got with matplotlib
- Alberto, we need to be extremely clear on the parameters we use (m, a,
  size, nb_runs, alpha=sqrt(nu1), gamma=sqrt(nu2)) because all the post
  process are based on these.
  Please provide a clear policy for parametrization, so we can produce data
  on our side
- Now I am reassured, because I know I am visualizing the RIGHT objects :)
  not something else,
  I can produce some more, but I'm waiting for your wishes and comments
  (the field of possibilities is getting very large as for now)
- If the parameters I've set are the right ones, then you have the list of
  degrees available to output the new degree distributions

Looking forward to your detailed answer (know that I won't be very
productive on that matter during next week)!

## 

Benjamin

**Comment by albertocottica** [comment]
Guy, I see that you have computed values setting the nu1s and nu2s of square root of 0.2, 0.4 etc. 

That sounds a bit strange, though. How do we justify that? Do we need to? 

Also notice: I have moved to the GitHub your results of 13th May, where nu1 == nu2 or onboarding == False.

**Comment by guywiz** [comment]
Not exactly.
When preparing for the Alicante talk, we decided to restrain computations to the case nu1 = nu2, and fpr some reason it made more sense that nu1_nu2 = 0.2, nu1_nu2 = 0.4, etc. in which case we indeed had nu1 = nu2 = sqrt(0.2) and so on. Moreover, at that time, I had set network_size = 650 because I thought we needed to have networks of size that compared with your empirical data.

Since then, I relaunched comptuations this time taking network_size = 2000 and letting nu1 and nu2 vary independently over [0.0, 0.2, 0.4, 0.6, 0.8, 1.0], not taking sqrt of anything when nu1 = nu2 (= 0.2, 0.4, ...).

**Comment by albertocottica** [comment]
Ok. @guywiz, just to be sure, could you re-upload to the repo the files in question? I mean:

True_0.0_0.0
True_0.2_0.2
True_0.4_0.4
True_0.6_0.6
True_0.8_0.8
True_1.0_1.0

**Comment by renoust** [comment]
Wow, so many posts in a day :)
So I see the parametrization is not cristal clear yet.

If I understand well, there is no difference between "nu1, nu2" and "alpha,
gamma"
This is a kind confusion we really need to avoid, because it make us
relaunch computations again and again.

So if possible, in the code, @Guywiz, please change alpha and gamma to nu1
and nu2, we'll then get rid
of all possible confusion.

This means I need to relaunch my own computations another time because
they're made upon sqrt(..) params.
Then I'm pushing a HOWTO file in the code section, discussing the
parameters.

## 

Benjamin

**Comment by albertocottica** [comment]
fixed (with an exception, that I will post into a separate issue)
