### ISSUE TITLE
Trouble with Latex

### ISSUE THREAD

**Issue by albertocottica** [albertocottica/communities-network-design#8]
Ben, I need some orientation with the Latex version of the paper. I have never used it outside of a sandbox. If we are to proceed with Latex, I need some support from you. At least two things: 
1. Latex seems to have a function for naming equations. For example, in the paper "formula" designates the symbol k. Is there somewhere where I can look up the list of equations with the corresponding names?
2. Citations break down. The error message is 

`LaTeX Warning: Citation `alstott2014powerlaw' on page 35 undefined on input line 44.`

Also, I may need help with figures :-(

**Comment by guywiz** [comment]
Almost anything with LaTeX can be referenced. Citations to bilbiographical entries are referenced t-using the \citation command, other entries are referenced using the \ref command.

If you look at the bibliography file (bibliography.bib), you see every entry has a label usually appearing on the first line. For example, I see the first paper in the file is labelled "zhang2007expertise". You cite this paper by inserting a \citation{zhang2007expertise} command. LaTeX introduces the proper refernce and takes care of including this paper in the bibliography.

As for the other types of entries. Suppose you write an equation, using the equation environment (\begin{equation} ... \end{equation}). You want to also insert a:
\label{eq:my_equation}
command so you can later refer to the euation in ths texte, linke in:
.. as confirmed by Eq. (\ref{eq:my_equation})

Got it?

The same holds for figures. When using the figure environment (\begin{figure} ... \end{figure}) you also want to introduce a label:
\label{fig:my_figure}
so you can refer to it using \ref:
... as illustrated in Fig. \ref{fig:my_figure}.

The figure environment is quite complex as it contains commands such as \includegraphics, and most of all \caption. You must introduce the label command _after_ the caption to help LaTeX refeence figures properly (don't ask me why, I never knew).

Now, the use of prefixes eq:, fig: etc. is not mandatory. it is there to help you find references in the text -- cos' no there is not easy way to collect all references used in the text but if your LaTeX editor does it for you.

I hope this helps.

**Comment by albertocottica** [comment]
Hah. I was looking at the Nature format, where Ben had included citations but they break for some reason. In the IEEE format citations work as normal. 

For now I will focus on redoing the data analysis work. When pictures come, we will see what to do.

**Comment by renoust** [comment]
Forget about the Nature Template, it seems broken, or it's just very
different because it's a different style of writing.
I have remade all bibtex and citation from the IEEE template (it was
hardcoded in the ODT).

Whenever you find a new interesting work to cite, it can be inserted as
follows: google to something like google scholar (in the settings activate
citations with bibtex), get the bibtex entry of the work you wanna cite,
for example it looks like this

@book{_cottica2010wikicrazia_,
  title={Wikicrazia: l'azione di governo al tempo della rete: capirla,
progettarla, viverla da protagonista},
  author={Cottica, Alberto},
  year={2010},
  publisher={Navarra}
}

notice the first line @XXX{ALIAS, here the alias is _cottica2010wikicrazia_
by convention, the ALIAS is often made with nameYearFirstword, but it could
be different
Now, in the text, you can cite this alias to get the box [123] as Guy said,
with \cite{ALIAS} or here \cite{_cottica2010wikicrazia}._

About the equations, LaTeX defines an environment of its own with
equations.

So let's say, you have two types of maths, the quick formula inserted
within text, is declare using : $f_0^1(x)$.
The dollars symbols state that inside is latex equations to interpret (here
is a tool to help you write your equations:
http://www.codecogs.com/latex/eqneditor.php)

The second equation environment is the
\begin{equation}
the\cup^n_iver\int e
\end{equation}
...
Basically, these begin / end come with wrappers that will allow to add a
number to the equation (like "Eq 1.1"), put space
before and after, stylise the whole thing etc.

The cool things are that you can add a label inside like this:

\begin{equation}
the\cup^n_iver\int e
\label{eq:the_universe}
\end{equation}

and then refer to it in the code, a little bit like citations:

"In the equation \ref{eq:the_universe} we prove nothing...."

Labels also work for sections, subsections... pictures, etc...

\section{Introduction}
\label{sec:intro}

"In Section \ref{sec:intro} we said that...."

Because we're talking environments, I have to mention similar mechanisms
for inserting figures and tables, considering the captions as well:

\begin{figure}
\label{fig:wonders}
\caption{This is a wonderful picture}
\end{figure}

I'll put some sample picture in the tex so you can copy/paste them, and
there must be an example table already.

Note also that we may stretch pictures and tables over the two columns with
a star (_) like \begin{figure_}

Here you go for a latex crash course. Don't worry, it's much simpler when
looking at the examples :)

## 

Benjamin
